### ISSUE TITLE
Rate constant expressions from kinetic gas theory

### ISSUE THREAD

**Issue by mhoffman** [ajmedford/catmap#32]
I would like to use rate constants from kinetic gas theory in a model (i.e.

     p_i*A_ij/sqrt(2*pi*m_i*kboltzmann*T)

as a rate constant for an adsorption.[1] As far as I can tell in catmap/data/templates.py[2] all rate constants have to be of the form 

    prefactor_list[i]*mpexp(-G_af[i]/(kB*T))

Am I therefore correctly assuming that one would have to enter the first expression into the prefactor? If so: I see that h and kB are explicitly passed into the template at the beginning of def rate_constants ...., is there some other proxy/vehicle where one could pass those other parameters (m_i, A_ij, s_i) ?

Any pointers are greatly appreciated.

[1] Actually I would also like to take this expression and multiply it with another exponent for the reverse (desorption).

[2] https://github.com/ajmedford/catmap/blob/master/catmap/data/templates.py#L106

**Comment by ajmedford** [comment]
Chuan is probably the expert on "non-standard" rate-constants, but it is likely more difficult than it should be since unfortunately I didn't take this into account when I coded things originally. I think you can hack around this by mapping the kinetic theory rate constant onto the exponential rate constant as you suggest, but just lump m_i, A_ij, and s_i into the prefactor since they will not change as a function of the descriptors. One thing to be aware of is that the "p_i" in your expression is already included since CatMAP uses rates of the form k_i*p_i*prod(theta_j).

**Comment by mhoffman** [comment]
Ok, for the record I should have added that A_ij is the active area of adsorption, s_i the sticking coefficient, and m_i the adsorbate mass. 
@chuanshi  I guess it would be a good idea to sit down together and put this in if you have a moment?

**Comment by chuanshi** [comment]
That sounds good to me, max.  Let's meet up after group meeting?

**Comment by mhoffman** [comment]
Sure.

**Comment by mhoffman** [comment]
To summarize the result of our discussion, the simplest solution for putting kinetic gas theory prefactors expression into rate constants would be to overwrite the default  `kB*T/h` by adding a variable `prefactor_list` in the inputfile `<model-name>.mkm`. 

The variable is a list of which each element has to evaluate to a number at runtime. Of course a simple number will always do here. By default the variable `kB` and `T` obviously can be used as well. The list has as many entries as the variable `rxn_expressions`.

If one doesn't want to overwrite the prefactor of a specific process one can simply leave write `None`.

So a valid example could be

    import math
    m = ...; A = ...; s = ...
    prefactor_list = [None, 1e8, 1e13, A*s/math.sqrt(2*math.pi*m_i*kB*T)
